# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/najib/Bureau/RPG2E

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/najib/Bureau/RPG2E

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/najib/Bureau/RPG2E/CMakeFiles /home/najib/Bureau/RPG2E/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/najib/Bureau/RPG2E/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RP2GE

# Build rule for target.
RP2GE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RP2GE
.PHONY : RP2GE

# fast build rule for target.
RP2GE/fast:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/build
.PHONY : RP2GE/fast

#=============================================================================
# Target rules for targets named serveur_tcp

# Build rule for target.
serveur_tcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serveur_tcp
.PHONY : serveur_tcp

# fast build rule for target.
serveur_tcp/fast:
	$(MAKE) -f CMakeFiles/serveur_tcp.dir/build.make CMakeFiles/serveur_tcp.dir/build
.PHONY : serveur_tcp/fast

serveur_TCP.o: serveur_TCP.c.o

.PHONY : serveur_TCP.o

# target to build an object file
serveur_TCP.c.o:
	$(MAKE) -f CMakeFiles/serveur_tcp.dir/build.make CMakeFiles/serveur_tcp.dir/serveur_TCP.c.o
.PHONY : serveur_TCP.c.o

serveur_TCP.i: serveur_TCP.c.i

.PHONY : serveur_TCP.i

# target to preprocess a source file
serveur_TCP.c.i:
	$(MAKE) -f CMakeFiles/serveur_tcp.dir/build.make CMakeFiles/serveur_tcp.dir/serveur_TCP.c.i
.PHONY : serveur_TCP.c.i

serveur_TCP.s: serveur_TCP.c.s

.PHONY : serveur_TCP.s

# target to generate assembly for a file
serveur_TCP.c.s:
	$(MAKE) -f CMakeFiles/serveur_tcp.dir/build.make CMakeFiles/serveur_tcp.dir/serveur_TCP.c.s
.PHONY : serveur_TCP.c.s

src/Attaque.o: src/Attaque.cpp.o

.PHONY : src/Attaque.o

# target to build an object file
src/Attaque.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Attaque.cpp.o
.PHONY : src/Attaque.cpp.o

src/Attaque.i: src/Attaque.cpp.i

.PHONY : src/Attaque.i

# target to preprocess a source file
src/Attaque.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Attaque.cpp.i
.PHONY : src/Attaque.cpp.i

src/Attaque.s: src/Attaque.cpp.s

.PHONY : src/Attaque.s

# target to generate assembly for a file
src/Attaque.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Attaque.cpp.s
.PHONY : src/Attaque.cpp.s

src/Client_sock.o: src/Client_sock.cpp.o

.PHONY : src/Client_sock.o

# target to build an object file
src/Client_sock.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Client_sock.cpp.o
.PHONY : src/Client_sock.cpp.o

src/Client_sock.i: src/Client_sock.cpp.i

.PHONY : src/Client_sock.i

# target to preprocess a source file
src/Client_sock.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Client_sock.cpp.i
.PHONY : src/Client_sock.cpp.i

src/Client_sock.s: src/Client_sock.cpp.s

.PHONY : src/Client_sock.s

# target to generate assembly for a file
src/Client_sock.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Client_sock.cpp.s
.PHONY : src/Client_sock.cpp.s

src/Gameplay.o: src/Gameplay.cpp.o

.PHONY : src/Gameplay.o

# target to build an object file
src/Gameplay.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Gameplay.cpp.o
.PHONY : src/Gameplay.cpp.o

src/Gameplay.i: src/Gameplay.cpp.i

.PHONY : src/Gameplay.i

# target to preprocess a source file
src/Gameplay.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Gameplay.cpp.i
.PHONY : src/Gameplay.cpp.i

src/Gameplay.s: src/Gameplay.cpp.s

.PHONY : src/Gameplay.s

# target to generate assembly for a file
src/Gameplay.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Gameplay.cpp.s
.PHONY : src/Gameplay.cpp.s

src/James.o: src/James.cpp.o

.PHONY : src/James.o

# target to build an object file
src/James.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/James.cpp.o
.PHONY : src/James.cpp.o

src/James.i: src/James.cpp.i

.PHONY : src/James.i

# target to preprocess a source file
src/James.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/James.cpp.i
.PHONY : src/James.cpp.i

src/James.s: src/James.cpp.s

.PHONY : src/James.s

# target to generate assembly for a file
src/James.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/James.cpp.s
.PHONY : src/James.cpp.s

src/Joueur.o: src/Joueur.cpp.o

.PHONY : src/Joueur.o

# target to build an object file
src/Joueur.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Joueur.cpp.o
.PHONY : src/Joueur.cpp.o

src/Joueur.i: src/Joueur.cpp.i

.PHONY : src/Joueur.i

# target to preprocess a source file
src/Joueur.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Joueur.cpp.i
.PHONY : src/Joueur.cpp.i

src/Joueur.s: src/Joueur.cpp.s

.PHONY : src/Joueur.s

# target to generate assembly for a file
src/Joueur.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Joueur.cpp.s
.PHONY : src/Joueur.cpp.s

src/Laffont.o: src/Laffont.cpp.o

.PHONY : src/Laffont.o

# target to build an object file
src/Laffont.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Laffont.cpp.o
.PHONY : src/Laffont.cpp.o

src/Laffont.i: src/Laffont.cpp.i

.PHONY : src/Laffont.i

# target to preprocess a source file
src/Laffont.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Laffont.cpp.i
.PHONY : src/Laffont.cpp.i

src/Laffont.s: src/Laffont.cpp.s

.PHONY : src/Laffont.s

# target to generate assembly for a file
src/Laffont.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Laffont.cpp.s
.PHONY : src/Laffont.cpp.s

src/Personnage.o: src/Personnage.cpp.o

.PHONY : src/Personnage.o

# target to build an object file
src/Personnage.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Personnage.cpp.o
.PHONY : src/Personnage.cpp.o

src/Personnage.i: src/Personnage.cpp.i

.PHONY : src/Personnage.i

# target to preprocess a source file
src/Personnage.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Personnage.cpp.i
.PHONY : src/Personnage.cpp.i

src/Personnage.s: src/Personnage.cpp.s

.PHONY : src/Personnage.s

# target to generate assembly for a file
src/Personnage.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/Personnage.cpp.s
.PHONY : src/Personnage.cpp.s

src/UI.o: src/UI.cpp.o

.PHONY : src/UI.o

# target to build an object file
src/UI.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/UI.cpp.o
.PHONY : src/UI.cpp.o

src/UI.i: src/UI.cpp.i

.PHONY : src/UI.i

# target to preprocess a source file
src/UI.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/UI.cpp.i
.PHONY : src/UI.cpp.i

src/UI.s: src/UI.cpp.s

.PHONY : src/UI.s

# target to generate assembly for a file
src/UI.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/UI.cpp.s
.PHONY : src/UI.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/RP2GE.dir/build.make CMakeFiles/RP2GE.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... RP2GE"
	@echo "... rebuild_cache"
	@echo "... serveur_tcp"
	@echo "... serveur_TCP.o"
	@echo "... serveur_TCP.i"
	@echo "... serveur_TCP.s"
	@echo "... src/Attaque.o"
	@echo "... src/Attaque.i"
	@echo "... src/Attaque.s"
	@echo "... src/Client_sock.o"
	@echo "... src/Client_sock.i"
	@echo "... src/Client_sock.s"
	@echo "... src/Gameplay.o"
	@echo "... src/Gameplay.i"
	@echo "... src/Gameplay.s"
	@echo "... src/James.o"
	@echo "... src/James.i"
	@echo "... src/James.s"
	@echo "... src/Joueur.o"
	@echo "... src/Joueur.i"
	@echo "... src/Joueur.s"
	@echo "... src/Laffont.o"
	@echo "... src/Laffont.i"
	@echo "... src/Laffont.s"
	@echo "... src/Personnage.o"
	@echo "... src/Personnage.i"
	@echo "... src/Personnage.s"
	@echo "... src/UI.o"
	@echo "... src/UI.i"
	@echo "... src/UI.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

